./fastchess.exe `
    -engine name="bk" cmd="$PSScriptRoot/../target/release/byte-knight.exe" `
    -engine name="bk1" cmd="$PSScriptRoot/../target/release/byte-knight.exe" `
    -each tc=0:10+1 `
    -draw movecount=2000 `
    -games 2 `
    -repeat `
    -output format=cutechess `
    -rounds 100 `
    -concurrency 20 `
    -sprt elo0=0 elo1=2 alpha=0.05 beta=0.05 `
    -openings file="$PSScriptRoot/../data/Pohl.epd" format=epd order=random
