name: Code coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  generate-coverage:
    runs-on: ubuntu-24.04
    steps:
      - name: Rust nightly
        run: |
          rustup default nightly
          rustup component add llvm-tools-preview
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install just
        uses: extractions/setup-just@v3
      - name: Install grcov
        run: |
          sudo apt update
          sudo apt install -y grcov
      - name: Install just
        uses: extractions/setup-just@v3
      - name: Generate coverage
        run: just coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/debug/coverage/byte-knight.lcov
