name: Build release binaries

on:
  push:
    tags:
      - "v*"
      - "*.*.*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: byte-knight
            extension: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: byte-knight
            extension: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: byte-knight.exe
            extension: ".exe"
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: byte-knight-${{ matrix.target }}${{ matrix.extension }}
          path: ./target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          retention-days: 1

      - name: Copy artifact
        run: cp ./target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ./target/${{ matrix.artifact_name }}-${{matrix.target}}${{ matrix.extension }}

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/${{ matrix.artifact_name }}-${{matrix.target}}${{ matrix.extension }}
