name: UCI Compliance
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Rust stable
        run: rustup default stable
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install just
        uses: extractions/setup-just@v2

      - name: Download fastchess
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh -R Disservin/fastchess release download v1.6.0-alpha -p "fastchess-linux-x86-64.tar"
          mkdir -p fast-chess
          tar -xf fastchess-linux-x86-64.tar -C fast-chess
          rm fastchess-linux-x86-64.tar

      - name: Build byte-knight
        run: just build release

      - name: Run UCI compliance tests
        run: |
          chmod +x fast-chess/fastchess
          ./fast-chess/fastchess-linux/x86-64/fastchess --compliance ./target/release/byte-knight
